### ISSUE TITLE
Build fails on Archlinux

### ISSUE THREAD

**Issue by SuspiciousDuck** [dnjulek/vapoursynth-zip#2]
When running `zig build -Doptimize=ReleaseFast` on Archlinux with zig at version `0.13.0`, there are 125 compilation errors. This is the error `no field named 'int' in enum '@typeInfo(builtin.Type).Union.tag_type.?'`

**Comment by dnjulek** [comment]
As you can see in [building](https://github.com/dnjulek/vapoursynth-zip?tab=readme-ov-file#building), this project uses zig master, so you'll need zig-0.14.0-dev

**Comment by SuspiciousDuck** [comment]
Didn't see that, sorry.
